# Generated by Django 4.1 on 2024-04-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                ("agency_id", models.AutoField(primary_key=True, serialize=False)),
                ("agency_name", models.CharField(max_length=255)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
                "ordering": ["agency_name", "disambiguator"],
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                ("apt_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("bedroom", models.IntegerField(blank=True, null=True)),
                ("bathroom", models.IntegerField(blank=True, null=True)),
                ("link", models.URLField(blank=True)),
                ("is_studio", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
                "ordering": ["apt_id"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("app_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["app_id"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                ("ava_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Availability",
                "verbose_name_plural": "Availabilities",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                ("period_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("rating_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "ordering": ["score"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["review_id"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("tenant_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("disambiguator", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_tenant",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="PrimeNest.apartment",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="PrimeNest.tenant",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="PrimeNest.apartment",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="PrimeNest.tenant",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="PrimeNest.apartment",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="PrimeNest.period",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="PrimeNest.apartment",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="PrimeNest.tenant",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="PrimeNest.agency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agency",
            constraint=models.UniqueConstraint(
                fields=("agency_name", "disambiguator"), name="unique_agency"
            ),
        ),
    ]
